### ISSUE TITLE
Download clarification

### ISSUE THREAD

**Issue by scamidge** [FreeTubeApp/FreeTube-Docs#136]
Using DASH & wanting both audio and video, I only have the choice of 360p. The setting for default video is 1080p. So how do I get a video of 1080p if available? Please clarify.

**Comment by absidue** [comment]
360p is the only stream that YouTube has with both audio and video, so if you want to any other quality, you need to download one of the video streams and then one of the audio streams and combine them with an external tool such as ffmpeg.
