### ISSUE TITLE
Bug: FreeTube Freezing before video starts

### ISSUE THREAD

**Issue by JackSparrow006** [FreeTubeApp/FreeTube-Docs#155]
When I load a video, sometimes it has this glich that it tries to load but then the whole application frezes, it happens randomly and the next video might work perfectly fine. I have no idea why this happened
![Screenshot_1](https://github.com/user-attachments/assets/b295eb2b-db27-4d8c-af8b-7323246171c5)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
see https://github.com/FreeTubeApp/FreeTube/issues/6334#issuecomment-2529906778
