### ISSUE TITLE
docs: include a reference to LibRedirect

### ISSUE THREAD

**Issue by SethFalco** [FreeTubeApp/FreeTube-Docs#20]
In `browser-extension.md`, Privacy Redirect is recommended. It seems there is a fairly popular fork called LibRedirect which also has FreeTube support.

It might be worth adding this to the documentation as well?

https://github.com/libredirect/libredirect

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Seems like Privacy Redirect was forked because of inactivity. Last commit was on 6 Dec 2021.
