### ISSUE TITLE
Data in the same repository for portable version

### ISSUE THREAD

**Issue by mathieucloutier86** [FreeTubeApp/FreeTube-Docs#85]
Hi,

Would be quite useful to have the data sits in the same repository for the portable version : i'd place it on an external hard drive and it would be always up to date and ready for automated backups.

To me, that's one of the most useful benefits of using a portable app instead of an installer. Would that be difficult to implement ?

Thank you,
Mathieu

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @mathieucloutier86 its better to open up a Q&A discussion over at our main repo, this way others will also benifit from the answer and non FT members can help u out. https://github.com/FreeTubeApp/FreeTube/discussions/new/choose
